### ISSUE TITLE
VoodooPS2 clarification

### ISSUE THREAD

**Issue by krisek** [meghan06/ChromebookOSX#18]
**Describe the issue**

The documentation refers in the 'Current status' table keyboard working with `VoodooPS2.kext` and trackpad working with `VoodooI2C.kext` and `VoodooI2CELAN.kext`.

On the other hand, in the 'Kext' listing `VoodooPS2Controller.kext` is mentioned.

I cannot find `VoodooPS2.kext` anywhere. If I load `VoodooI2C.kext` and `VoodooI2CELAN.kext` trackpad works, but no keyboard, as it conflicts with `VoodooPS2Controller.kext`.  With `VoodooPS2Controller.kext` loaded it doesn't even get to the rescue environment.

Maybe I'm missing some crucial aml's?

Any hints? As this is my first MacOS install on PC, I must be missing something. 

**Versions (please complete the following information):**
 - OS: tried with Monterey and Ventura
 - OC Version: latest

**Device (please complete the following information):**
 - Device: Asus C433

**Comment by krisek** [comment]
Apparently, if I add

VoodooI2C.kext
VoodooI2CELAN.kext

(from VoodooI2C-2.8.zip)

VoodooPS2Keyboard.kext in VoodooPS2Controller.kext (from VoodooPS2Controller-2.3.5-RELEASE.zip from your repo)

then it starts both touchpad and keyboard working.

Next hurdle... if I connect to a wireless network the rescue environment freezes.

**Comment by krisek** [comment]
Wireless is up, all good, next one is eMMC storage support, we'll see if I manage.

I think, I close this issue, no need to keep open loose threads.

**Comment by meghan06** [comment]
Sorry, forgot to reply. Glad you figured it all out. 
eMMC should be working, as long as you have EmeraldSDHC and HPET patches. 

To answer some of your older questions,

Freeze when connecting to WiFi was caused by `ProtectMemoryReigons` being set to true in your config.plist. That should be disabled.

You need all 3 Voodoo kext's for input to function.

**Comment by krisek** [comment]
Thanks for coming back on this, much appreciated!

I'll raise a PR on Voodoo's if you don't mind, because it took a little time to figure out which three Voodoo kext are needed.

Wifi: during my desperate attempts to get keyboard and touchpad working I switched to `Monterey`, while `Airportitlwm` was left on `Ventura` --- the problem was between the chair and the keyboard, which doesn't strictly belong to this issue :)

`EmeraldSDHC` seems to be something tricky: `SSDTTime`  dumps `DSDT.aml`, generates `SSDT-HPET.{aml,dsl}` and `patches_OC.plist` with the following patches:

- HPET _STA to XSTA Rename
- HPET _CRS to XCRS Rename
- PIC IRQ 2 Patch
- TIMR IRQ 0 Patch

The weird thing is that it doesn't matter which option I choose in `FixHPET` I get the same files/patches generated.

**Comment by meghan06** [comment]
For eMMC, you need to do the following:
- Dump DSDT
- Feed DSDT to SSDTTime
- Seledt FixHpet and choose C
- Drag SSDT-HPET.aml to ACPI folder
- Find patches_oc.plist and drag the patches into your config.plist
- Note that after you do this you should never do a clean snapshot on ProperTree (ctrl shift r), only do regular snapshots (ctrl r)

Ask in the chrultrabook discord if you want quicker reply times. I don't check this repo often because I am quite busy, you will be better off asking in there as I do check Discord more than Github.

**Comment by krisek** [comment]
Thanks a lot for the hint, I'll drop by!
