### ISSUE TITLE
Stuck on booting

### ISSUE THREAD

**Issue by tranmylinhvn** [meghan06/ChromebookOSX#2]
Stuck on booting: AppleIntelLpssI2CController::_serviceMatchingTimeSubr : fTimerServiceMatching timed out, fNotifications 0
And a 'block' sign.
Please help me.
![IMG_2798](https://user-images.githubusercontent.com/85661932/218111199-d1a1e518-e14a-40e7-b1e1-1dcb8d41249d.JPG)
[EFI.zip](https://github.com/meghan06/ChromebookOSX/files/10708131/EFI.zip)

**Comment by meghan06** [comment]
the block sign (prohibited symbol 🚫) suggests a USB mapping issue. If remapping USB doesn't work, you can try adding SSDT-XOSI and it's corresponding patch to see if that'll work.

**Comment by meghan06** [comment]
Also, do you get this when booting the installer? or...

**Comment by tranmylinhvn** [comment]
I already have remapping USB port and Add SSDT-XOSI but same error (AppleIntelLpssI2CController::_serviceMatchingTimeSubr : fTimerServiceMatching timed out, fNotifications 0)
![image](https://user-images.githubusercontent.com/85661932/218224330-74f88040-16de-400f-a655-32538a4684d7.png)
![IMG_2799](https://user-images.githubusercontent.com/85661932/218224421-48a1270d-eb90-4091-88f0-7439e6ad556e.JPG)

[EFI.zip](https://github.com/meghan06/ChromebookOSX/files/10712083/EFI.zip)

 I get error when I'm try to install.

Can you check my EFI folder for me?

Also, please reup file EmeraldSDHC.kext because I can not download it.

**Comment by meghan06** [comment]
Seems like you're still mapping the USB incorrectly, IIRC the ports you want should be green but I don't think that should cause any major issues since its still in your USB Map. Just an FYI, you missed Port 1 which is one of your USB-C Ports.  Also, if you're using USBToolBox, you need a separate kext that goes along with it. So, it will be your UTBMap.kext and USBToolBox kext. Download is [here.](https://github.com/USBToolBox/kext) Without it, USBToolBox will not work. This may be the cause.

If that doesn't work, there is another way to map USB though, and that is by installing macOS 10.15 or older with USBInjectAll and mapping your USB ports via USBMap rather than USBToolbox. macOS 10.15 and older are less strict with the USB ports, so enabling XchiPortLimit and using USBInjectAll will work. Map your USB ports there, and save the kext so you can reuse it. Don't do this unless USBTooLBox simply refuses to work.

EmeraldSDHC is still a developer beta, so there is no download on the release page. You can still download its precompiled binaries in its Actions page. [here](https://github.com/acidanthera/EmeraldSDHC/actions/runs/4075408957) under "Artifacts". You need to be signed into a GitHub account in order to download Artifacts.

I hope I helped. You can find more information in the chrultrabook Discord server, where it has a dedicated section for hackintoshes along with the r/hackintosh paradise Discord server, which is for Hackintoshes in general. You will receive faster support there too. 

chrultrabook discord: https://discord.com/invite/tkPTk5w
r/Hackintosh Paradise discord: https://discord.gg/u8V7N5C

Hope this helped. 
Cheers!

**Comment by meghan06** [comment]
Also you can delete SSDT-XOSI since I believe its an USB Issue.

**Comment by meghan06** [comment]
Looking thru your config.plist, I see several errors.
- Under DeviceProperties in your iGPU section, you have unnecessary patches. All you need is AAPL,ig-platform-id. You don't need the other patches.
-  You also forgot to enable ProtectMemoryReigons under ACPI->Booter->Quirks
- XCHIPortLimit is enabled, not sure why it is. If you're booting macOS 11 and newer, turn this OFF. Kernel-> Quirks.

Id suggest re reading the config.plist setup for Kaby Lake Laptop and this guide without skipping anything since you messed up some pretty significant parts. XHCIPortLimit might even be the cause for your issues.

**Comment by tranmylinhvn** [comment]
I have add USBToolBox kext and your instruction had been work. Like a charm.
Thanks for your help.
![IMG_2816](https://user-images.githubusercontent.com/85661932/218246003-14604370-f84b-45a4-915d-6d1de083b8a3.JPG)

![IMG_2817](https://user-images.githubusercontent.com/85661932/218246012-df22ed47-b00d-44fd-a881-9d39bd673c39.JPG)

**Comment by meghan06** [comment]
Nice! Secure Digital Physical Volume is the eMMC. Don't forget to click Show->View all devices or something like that and erase the whole drive, or you will have a 100 mb EFI which will cause issues.
